version: '3'
services:
    node_app:
        build: .
        container_name: node_app
        volumes: 
            - ./:/usr/src/app/
            - /usr/src/app/Backend/node_modules
        ports:
            - 8080:8080

    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - ./mongodb/data:/data/db
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root